version: '3.8'
services:
  downloader:
    build: .
    environment:
      - DIAS=-1
    volumes:
      - ./animes.db:/app/animes.db
    restart: unless-stopped

  anime_downloader_7d:
    build: .
    environment:
      - DIAS=2
    volumes:
      - ./animes.db:/app/animes.db
    restart: unless-stopped
